baseURL = 'https://w-k-s.github.io/'
languageCode = 'en-us'
title = 'W K S'
theme = "binario"

[Author]
  name = "Waqqas"
  bio = "Backend Tech Lead"
  avatar = "https://avatars.githubusercontent.com/u/3167727"


[Params]
  description = "Tech blog + Stories about my life" # Site Description. Used in meta description
  copyright = "Waqqas Sheikh" # Copyright holder, otherwise will use .Site.Title
  opengraph = false # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  columns = 2 # Set the number of cards columns. Possible values: 1, 2, 3
  mainSections = ["post","about"] # Set main page sections
  dateFormat = "January 02, 2006" # Change the format of dates
  colorTheme = "dark-blue" # dark-green, dark-blue, dark-red, dark-violet
  mainMenuAlignment = "right" # Align main menu (desktop version) to the right side
  authorbox = true # Show authorbox at bottom of single pages if true
  comments = false # Enable comments for all site pages
  related = true # Enable Related content for single pages
  relatedMax = 5 # Set the maximum number of elements that can be displayed in related block. Optional
  mathjax = false # Enable MathJax for all site pages
  hideNoPostsWarning = false # Don't show no posts empty state warning in main page, if true

[Params.Entry]
  meta = ["date", "categories", "tags"] # Enable meta fields in given order
  toc = true # Enable Table of Contents
  tocOpen = true # Open Table of Contents block. Optional

[Params.Featured]
  previewOnly = false # Show only preview featured image

[Params.Breadcrumb]
  enable = true # Enable breadcrumb block globally
  homeText = "w-k-s" # Home node text

[Params.Social]
  email = "blog@wks.anonaddy.com"
  linkedin = "waqqas-sheikh"
  github = "w-k-s"
  stackoverflow = "821110"